site_name: RadiantOS
site_description: A sleek unix-inspired pseudo-operating system built on web technology.
site_url: https://frqstbite.github.io/radiantos
repo_name: frqstbite/radiantos
repo_url: https://github.com/frqstbite/radiantos

extra:
  version:
    provider: mike

extra_css:
  - assets/stylesheets/theme/radiant.css
  - assets/stylesheets/theme/theme.css

theme:
  name: material
  custom_dir: docs/assets/overrides
  logo: assets/images/logo-dark.svg
  favicon: assets/images/logo-dark.svg
  palette:
    - media: '(prefers-color-scheme: dark)'
      scheme: radiant-dark
      primary: black
      toggle:
        icon: octicons/sun-24
        name: '➔ LIGHT'
    - media: '(prefers-color-scheme: light)'
      scheme: radiant-light
      primary: black
      toggle:
        icon: octicons/moon-24 
        name: '➔ DARK'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - search.suggest
    - search.highlight
  icon:
    repo: octicons/mark-github-16

nav:
  - Home: index.md
  - Guides:
    - guides/index.md
    - Creating An Application:
      - Introduction: guides/application/index.md
      - Project Setup: guides/application/setup.md
    - Creating A Kernel Module:
      - Introduction: guides/module/index.md
      - Project Setup: guides/module/setup.md
  - API Reference:
    - Home: api-reference/index.md
    - Application API:
      - files Module: api-reference/application/files.md
    - Kernel API:
      - filesystem Module: api-reference/kernel/files.md

plugins:
  - social:
      cards_layout_options:
        background-color: "#0f1a24" #Valorant navy
        color: "#ff4655" #Valorant red
        font_family: Ubuntu

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences